### ISSUE TITLE
stucks at [INFO] Loading ShrecNet..

### ISSUE THREAD

**Issue by NandhaKishorM** [sriramsk1999/gestures-mediapipe#3]
The code freezes at 2020-09-30 16:58:02,672 [INFO] Loading ShrecNet.. Ubuntu 18.04

**Comment by sriramsk1999** [comment]
Hello, could you please elaborate on the problem? From what you've said I can tell that you've run `gesture_receiver.py` successfully. That file is one half of the application i.e. the receiving half of the keypoints.

For the keypoints to be generated and sent to `gesture_receiver.py`, you must build and run the mediapipe executable, as described in the README. While the executable is running, if you run the `gesture_receiver` script, it should work. Both programs must be running together for usage.

Let me know if you have any further questions.

**Comment by NandhaKishorM** [comment]
Should I have to clone the mediapipe repository on separate directory,
build it and copy the bazel binary to this directory

**Comment by sriramsk1999** [comment]
A simpler approach (and the one described in the README) is to setup mediapipe and then clone this repo *in* mediapipe

**Comment by NandhaKishorM** [comment]
Let me try and update it to you, cheers

**Comment by NandhaKishorM** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'data/static_gesture_mapping.json'
even if I set python path as export PYTHONPATH=$(pwd)

**Comment by NandhaKishorM** [comment]
this happens when I run from mediapipe directory. But after i run from the gesture directory it works, but nothing happens even I run the mediapipe execution parallel. No mouse movement

**Comment by NandhaKishorM** [comment]
![Screenshot from 2020-09-30 19-29-45](https://user-images.githubusercontent.com/48623612/94695459-901e3600-0353-11eb-954c-c1708530b6cd.png)

**Comment by sriramsk1999** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'data/static_gesture_mapping.json'
> even if I set python path as export PYTHONPATH=$(pwd)

Ah, I'd missed that. Thanks for the catch, I'll push a commit and fix this.

> this happens when I run from mediapipe directory. But after i run from the gesture directory it works, but nothing happens even I run the mediapipe execution parallel. No mouse movement

That is strange. Are you using the mediapipe executable specified in the README? Compiled and executed using the instructions [here](https://github.com/sriramsk1999/gestop#mediapipe-executable)?

**Comment by NandhaKishorM** [comment]
yes. I build it using the extact instructions

**Comment by NandhaKishorM** [comment]
is it something related to __post__init(self)

**Comment by sriramsk1999** [comment]
Okay so I had a look, and figured that you were using the CPU version, while I only use the GPU version. I tested out the CPU version and it didn't work so I can reproduce the bug. 

I'll look into it and get back to you with a fix. Thanks for raising the issue!

**Comment by NandhaKishorM** [comment]
thanks. Looking forward to it

**Comment by sriramsk1999** [comment]
I've pushed some changes that should hopefully fix the issue. Could you pull the latest commits and rebuild the application?

**Comment by NandhaKishorM** [comment]
Ohk. Lemme try and update you 👍

**Comment by NandhaKishorM** [comment]
127.0.0.1
Server Connection Failed 
I think the server is not connecting . The zmq can't listen. Still no luck in running

**Comment by sriramsk1999** [comment]
Are you sure you have the latest commits? In particular, in `hand_tracking_landmarks_cpu..cc` , is [this](https://github.com/sriramsk1999/gestop/blob/a1ad918f48ac15406e2797a807335627584c4cc5/hand_tracking_landmarks_cpu.cc#L59) flag set to 1 and **not** 0?

**Comment by NandhaKishorM** [comment]
ERROR: /home/nandu/Desktop/mediapipe/gestop/BUILD:36:10: //gestop:zeromq: missing input file '//gestop:zmq.hpp'
Target //gestop:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/nandu/Desktop/mediapipe/gestop/BUILD:36:10 1 input file(s) do not exist
INFO: Elapsed time: 15.750s, Critical Path: 0.83s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by NandhaKishorM** [comment]
latest commit throwing this error. So I built it using previous one

**Comment by sriramsk1999** [comment]
Please use only the latest versions in future comments, it's harder to debug if we are not on the same page. 
As for the BUILD error, have you completed all the steps in the README?
`
ZeroMQ - The zeromq library (libzmq.so) must be installed and symlinked into this directory. The header only C++ binding cppzmq must also be installed and its header (zmq.hpp) symlinked into the directory.
`

**Comment by NandhaKishorM** [comment]
ERROR: /home/nandu/Desktop/mediapipe/gestop/BUILD:84:11: C++ compilation of rule '//gestop:hand_tracking_landmarks_cpu' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
gestop/hand_tracking_landmarks_cpu.cc: In function 'mediapipe::Status RunMPPGraph()':
gestop/hand_tracking_landmarks_cpu.cc:208:20: error: 'buffer' is not a member of 'zmq'
     sock.send(zmq::buffer(output), zmq::send_flags::dontwait);
                    ^~~~~~
gestop/hand_tracking_landmarks_cpu.cc:208:41: error: 'zmq::send_flags' has not been declared
     sock.send(zmq::buffer(output), zmq::send_flags::dontwait);
                                         ^~~~~~~~~~
Target //gestop:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 22.235s, Critical Path: 19.81s
INFO: 0 processes.

**Comment by NandhaKishorM** [comment]
created symbolic link for libzmq.so,zmq.hpp. But showing this error

**Comment by sriramsk1999** [comment]
It appears to be a problem with your zmq installation. Can you run the first example [here](https://github.com/zeromq/cppzmq/#examples) and check if it runs successfully? Compile with `g++ file.cpp -lzmq`

**Comment by NandhaKishorM** [comment]
test.cc: In function ‘int main()’:
test.cc:8:20: error: ‘str_buffer’ is not a member of ‘zmq’
     sock.send(zmq::str_buffer("Hello, world"), zmq::send_flags::dontwait);
                    ^~~~~~~~~~
test.cc:8:53: error: ‘zmq::send_flags’ has not been declared
     sock.send(zmq::str_buffer("Hello, world"), zmq::send_flags::dontwait);

**Comment by NandhaKishorM** [comment]
this is the error after running the test script

**Comment by sriramsk1999** [comment]
Okay looks like we've isolated the problem. There's something wrong with your zmq/cppzmq installation. I would suggest making sure that you have the latest versions of zmq and cppzmq, or opening an issue on their [repo](https://github.com/zeromq/cppzmq/).

**Comment by NandhaKishorM** [comment]
thanks it worked.

**Comment by NandhaKishorM** [comment]
Thank you for your time and effort for replying to my queries instantly. Great job for making this work

**Comment by sriramsk1999** [comment]
Glad to hear it! :)
